#server:
#  port: 9001
#spring:
#  application:
#    name: skyln-user-service
#  redis:
#    host: 192.168.121.128
#    password: redisPWD
#    port: 6379
#    lettuce:
#      pool:
#        # 连接池最大连接数（使用负值表示没有限制）
#        max-active: 10
#        # 连接池中的最大空闲连接
#        max-idle: 10
#        # 连接池中的最小空闲连接
#        min-idle: 0
#        # 连接池最大阻塞等待时间（使用负值表示没有限制）
#        max-wait: -1ms
#  zipkin:
#    base-url: http://192.168.121.130:9411/ #zipkin地址
#    discovery-client-enabled: false  #不用开启服务发现
#  sleuth:
#    sampler:
#      probability: 1.0 #采样百分比
#  cloud:
#    sentinel:
#      transport:
#        dashboard: 192.168.121.130:8080
#        port: 8920
#    nacos:
#      discovery:
#        server-addr: 192.168.121.130:8848
#  #数据库配置
#  datasource:
#    driver-class-name: com.mysql.cj.jdbc.Driver
#    url: jdbc:mysql://192.168.121.130:3306/skyln_user?useUnicode=true&characterEncoding=utf-8&useSSL=false&serverTimezone=Asia/Shanghai
#    username: root
#    password: root
#
##配置plus打印sql日志
#mybatis-plus:
#  configuration:
#    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
#
##设置日志级别,ERROR/WARN/INFO/DEBUG,默认是INFO以上才显示
#logging:
#  level:
#    root: INFO
#
##修改负载均衡策略为根据响应时间
##xdclass-user-service:
##  ribbon:
##    NFLoadBalancerRuleClassName: com.netflix.loadbalancer.WeightedResponseTimeRule
#
##开启Feign对Sentinel的支持
#feign:
#  sentinel:
#    enabled: true
